### ISSUE TITLE
issue with SoniaLegacyPatcher.sh

### ISSUE THREAD

**Issue by fqrums** [ArchiverXP/Sonia#2]
![image](https://github.com/user-attachments/assets/83ed84f9-0ee5-4633-8f7c-b6b50577b1dd)
It always gives this error no matter what, i dont even know where to find this dylib, otherwise the other 2 sh files work fine.

**Comment by fqrums** [comment]
nvm im just stupid

**Comment by fqrums** [comment]
![image](https://github.com/user-attachments/assets/c4756973-929f-4f7d-af27-f7d74054e1d2)
this is what i got after trying to "compile" the GameController.x file.

**Comment by ArchiverXP** [comment]
Doesn't happen on my end for some whatever reason, what version is your Theos?

**Comment by fqrums** [comment]
Latest, i literally just installed the vm for this lol

**Comment by ArchiverXP** [comment]
Ah, alright.
Well I tried the latest and it worked for me, maybe try updating your make?
I have the latest make and it compiles just fine.

**Comment by fqrums** [comment]
> Ah, alright. Well I tried the latest and it worked for me, maybe try updating your make? I have the latest make and it compiles just fine.

Okay looks like it was a make and a sdk issue. thanks
